#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspborder &
flameshot &
dunst &

bspc monitor -d I II III IV V
bspc config border_width 4
bspc config window_gap 15

bspc config focused_border_color "#abb2bf"
bspc config normal_border_color "#abb2bf"
bspc config active_border_color "#abb2bf"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a Code desktop='^5'
bspc rule -a Zathura state=tiled
